#!/bin/sh

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
  echo "Прямой push в main запрещен"
  echo ""
  echo "Используй ветки:"
  echo "  feat/..."
  echo "  fix/..."
  echo ""
  echo "Пример:"
  echo "  git checkout -b feat/graph-editor"
  echo ""
  exit 1
fi