#!/bin/sh

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "main" ]; then
  echo "Rebase main ветки запрещен"
  echo ""
  echo "Переключись на рабочую ветку:"
  echo "  git checkout feat/your-task"
  echo ""
  exit 1
fi