#!/bin/sh

COMMIT_MSG_FILE="$1"
COMMIT_SOURCE="$2"

if [ -z "$COMMIT_SOURCE" ]; then
  cat <<'EOF' > "$COMMIT_MSG_FILE"
# Формат:
#   <type>(<scope>): <description>
#
# Scope необязателен
#
# Примеры:
#   feat(graph): add vertex creation
#   fix(scene): prevent duplicate edges
#   docs: update README
#
# Допустимые type:
#   feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert, hotfix
#
EOF
fi